name = "nvrs-hono"
main = "index.js"
compatibility_date = "2023-01-01"

[build]
command = "npm run build"

[site]
bucket = "./public"

[env.production]
route = "vrsprototype.com/*"

node_compat = true
